package org.predictor.picoplaca.main;

import org.predictor.picoplaca.builder.PicoYPlacaBuilder;
import org.predictor.picoplaca.exception.ConversionException;
import org.predictor.picoplaca.model.PicoYPlaca;
import org.predictor.picoplaca.validation.Validators;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        try {
            if (args.length != 3) {
                System.out.println("Please provide exactly 3 arguments: A license plate number, a date and a time.");
                return;
            }
            PicoYPlaca picoYPlaca = PicoYPlacaBuilder.getINSTANCE().build(args[0], args[1], args[2]);
            Validators.validate(picoYPlaca);
        } catch (ConversionException e) {
            System.out.println(e.getMessage());
        }
    }
}
